name: Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: 📦 Instalar dependências
        run: yarn install

      - name: ✅ Rodar testes com coverage
        run: yarn test --coverage

      - name: 📊 Gerar badge de cobertura
        run: |
          yarn add --dev coverage-badge-cli
          npx coverage-badge -o coverage/badge.svg

      - name: 💾 Salvar HTML do coverage como artefato
        uses: actions/upload-artifact@v4.6.2
        with:
            name: coverage-report
            path: coverage/lcov-report/

      - name: 💾 Salvar badge como artefato
        uses: actions/upload-artifact@v4.6.2
        with:
            name: coverage-badge
            path: coverage/badge.svg

